### ISSUE TITLE
Something is unstable about latest master

### ISSUE THREAD

**Issue by johnnyshields** [collectiveidea/delayed_job#839] opened 2015-08-17 20:12 UTC
I tried upgrading from 4.0.6 to latest master and the process keeps exiting in production after errors within the jobs. I don't know the root cause yet.

**Comment by albus522** [comment] 2015-08-18 14:13
What do the logs say after it exits?

**Comment by Jesus** [comment] 2015-08-18 15:03
What kind of errors are the jobs raising? `ArgumentError`, `NotImplementedError`, etc.

**Comment by johnnyshields** [comment] 2015-08-18 18:12
The error is being caught and raised by `Delayed::Command#run` as per lines below:

```
    def run(worker_name = nil, options = {})
      ### ERROR HAPPENING AFTER HERE
      Dir.chdir(root)

      Delayed::Worker.after_fork
      Delayed::Worker.logger ||= Logger.new(File.join(@options[:log_dir], 'delayed_job.log'))

      worker = Delayed::Worker.new(options)
      worker.name_prefix = "#{worker_name} "
      worker.start
      ### ERROR HAPPENING BEFORE HERE
    rescue => e
      STDERR.puts e.message
      STDERR.puts e.backtrace
      ::Rails.logger.fatal(e) if rails_logger_defined?
      exit_with_error_status
    end
```

The process exists after error is logged. I have a custom lifecycle callback around `:invoke_job` to log errors to Bugsnag, but this callback is **NOT** triggered so the failure is somewhat silent (!)

The error is a database error related to being unable to find a document (it is raised by Mongoid library; error base class is `StandardError`). Presumably this error is happening somewhere inside my workers.

Rolling back to 4.0.6 fixes the issue.

I have not had time to debug further, but wanted to first raise a red flag that something significant has changed, and it bit me in production.

**Comment by VijayMs** [comment] 2015-09-10 13:37
Have you checked for deadlock errors in logs?. This could be the reason sometimes.

**Comment by johnnyshields** [comment] 2015-09-10 14:06
@VijayMs doubt this is a deadlock as process is exiting. Seems to be a case of an error within a job leaking out and causing a crash

**Comment by VijayMs** [comment] 2015-09-10 14:49
@johnnyshields when a deadlock is encountered, it will raise an exception `Mysql::Error: Deadlock`(depends on db you are using.) which is not handled. This leads to killing the jobs. When it encounters deadlock one transaction get succeeded but another one will end up with exception. We have to rescue and retry that transaction. This will prevent from killing the jobs. Could you go through the logs for any delayed job exceptions, as this will be help full to fix your problem.

**Comment by VijayMs** [comment] 2015-09-10 14:57
@albus522  `2015-07-29T22:47:45+0200: [Worker(delayed_job.15] Job -- (id=233636781) FAILED (0 prior attempts) with ActiveRecord::StatementInvalid: Mysql::Error: Deadlock found when trying to get lock; try restarting transaction: DELETE FROM `delayed_jobs` WHERE `delayed_jobs`.`id` = ?`. This exception kills the job.

**Comment by VijayMs** [comment] 2015-09-10 15:40
@albus522 `raise FatalBackendError if @failed_reserve_count >= 10` and `count = ready_scope.limit(1).update_all(locked_at: now, locked_by: worker.name)`. Here `update_all` may raise `Mysql::Error`: for deadlock. So after 10 times the deadlock occurs, our code will raise `FatalBackendError` this will kill the job.

**Comment by albus522** [comment] 2015-09-11 14:20
That is 10 deadlocks in a retry loop. Basically that is never going to complete so the only thing we can do is exit.

This is usually caused by creating a ton of very fast jobs. DJ was never intended to delay things that would execute quickly inline.

Other possible causes are a stuck worker that has obtained DB locks on things it shouldn't have or DB level operations that lock the table. Examples of locking DB level operations are backups (DB dumps), optimize, and vacuum commands

**Comment by VijayMs** [comment] 2015-09-11 15:53
@albus522 The deadlock happens not on table level, it is on indies level https://github.com/collectiveidea/delayed_job_active_record/issues/63#issuecomment-21452795. We have to retry once to succeed the transaction. And for this deadlock condition we don't need tons of jobs. when we try to delete the job and reserve a job and both at same index page, then deadlock will encounter. This should not count as exception when we can recover from it. But we can count when it fails in retry also. It is better to retry only once or thrice. This will solve the problem.

**Comment by VijayMs** [comment] 2015-09-11 15:54
Comment in the github issue page:

We were bit by this as well during an upgrade.

I set up a concurrency test on my dev machine using two workers and a self-replicating job. The job simply creates two more of itself, with semi-random priority and run_at values. This setup reliably repros the deadlock within seconds.

The output of show engine innodb status says the contention is between the UPDATE query now used to reserve a job, and the DELETE query used to clean up a finished job. Surprising! Apparently the DELETE query first acquires a lock on the primary index (id) and then on the secondary index (priority, run_at). But the UPDATE query is using the (priority, run_at) index to scan the table, and is trying to grab primary key locks as it goes. Eventually the UPDATE and DELETE queries each grab one of two locks for a given row, try to acquire the other, and ￼. MySQL resolves by killing the UPDATE, which crashes the worker.

The fix I've worked out locally is to replace the index on (priority, run_at) with an index on (priority, run_at, locked_by). This completely stabilizes my concurrency test! My theory is that it allows the UPDATE query's scan to skip over rows held by workers, which takes it out of contention with the DELETE query.

Hope this helps.

**Comment by johnnyshields** [comment] 2015-09-22 17:40
I think https://github.com/collectiveidea/delayed_job/pull/846 is a plausible candidate for my original issue I encountered. @VijayMs issue may be something else.

**Comment by sferik** [comment] 2015-09-22 20:54
Resolved by https://github.com/collectiveidea/delayed_job/pull/846. Please reopen if that doesn’t fix your issue.

**Closed by sferik** 2015-09-22 20:54 UTC

**Comment by VijayMs** [comment] 2015-09-23 10:54
@johnnyshields  thanks for your reply. In my case deadlock was the problem.
