### ISSUE TITLE
raise_signal_exceptions not working for enqueued job

### ISSUE THREAD

**Issue by sterankin** [collectiveidea/delayed_job#1008] opened 2017-12-06 17:20 UTC
I have 2 long running jobs.  The first one runs on a schedule, and when it finishes it then enqueues the second job like this:

`Delayed::Job.enqueue(NextJob.new)`

I have a max run time of 2 hours.  I my delayed job config initializer I have the following:

Delayed::Worker.raise_signal_exceptions = true

This works fine for the first job, but when the second job is started, it is not killed when it hits max run time.  It fails the job but it then continues processing until it finishes.  It seems it does not pay attention to the raise_signal_exceptions flag.

Can I add a method to the other job like this:

```
  def raise_signal_exceptions
    true
  end
```

would that ensure the second job would be killed if it goes past the max run time?

**Comment by albus522** [comment] 2017-12-06 17:52
`raise_signal_exceptions` has nothing to do with a job timeout.

Regarding max run time, I suspect things are working exactly as intended in your case. My guess is that the job does fail and the continued processing you are seeing is because it immediately retries the job. DJ has an exponential backoff on the retry, but the first retry is pretty much immediately.

**Comment by sterankin** [comment] 2017-12-06 18:23
When a job times out, by default it finishes what it is doing unless you set raise_signal_exceptions to true, in which case it sends a SIGTERM to stop it immediately.

I also have max retries set to 1.

**Comment by albus522** [comment] 2017-12-06 19:15
No, that is not correct. When max run time is reach the job is immediately killed and queued for retry. The ONLY impact `raise_signal_exceptions` has is exactly what it says, when the DJ process receives SIGINT or SIGTERM the appropriate signal exception is raised in the process. It has no impact what so ever on max run time.

For handling max run time we use the ruby timeout library. There are several known issues with things that can slip past the ruby timeout library. If your job continues to run, and not as a retry, after the timeout, it means your job is triggering one of those issues. Off the top of my head, I think one of them was certain types of network calls.

**Comment by sterankin** [comment] 2017-12-06 19:24
Thanks for the comment, the behaviour I am seeing, and this comment on the delayed job code leaves me to believe otherwise.  The comment suggests that the worker will finish the job, my job can take hours and the job does continue until it is finished:

 # By default, Signals INT and TERM set @exit, and the worker exits upon completion of the current job.
    # If you would prefer to raise a SignalException and exit immediately you can use this.
    # Be aware daemons uses TERM to stop and restart
    # false - No exceptions will be raised
    # :term - Will only raise an exception on TERM signals but INT will wait for the current job to finish
    # true - Will raise an exception on TERM and INT

**Comment by albus522** [comment] 2017-12-06 19:42
Take a look at who wrote it https://github.com/collectiveidea/delayed_job/commit/90579c3047099b6a58595d4025ab0f4b7f0aa67a

Job timeouts do NOT trigger any unix process signals. `raise_signal_exceptions` is all about unix process signals. When `raise_signal_exceptions` is `false` the running job has no idea the process has been asked to quit, so the job runs until it completes or the max run time is reached, then the worker gracefully exits. When `raise_signal_exceptions` is configured and the process receives a unix process signal we raise the appropriate signal exception in whatever code is currently running. This can be your job code if a job is executing when the signal is received. DJ will never trigger a unix process signal

**Comment by anhadgill23** [comment] 2020-11-27 20:53
@albus522 is there a way to capture this signal exception to clean up before the shutdown? I was looking to use the Interrupt error handling class but active jobs `rescue_from` block only allow StandardError handling.

**Comment by joshuapinter** [comment] 2021-01-05 15:29
I believe we can close this issue as the issue lies outside of `delayed_job` and with your daemon / process manager.

**Comment by albus522** [comment] 2024-07-26 19:46
Closing stale

**Closed by albus522** 2024-07-26 19:46 UTC
